version: "3"
services:

  nginx_proxy:
    image: nginx:1.21.5-alpine
    volumes:
     - ./services/nginx_proxy/config:/etc/nginx/conf.d
     - ./services/nginx_proxy/certs:/etc/nginx/certs
    ports:
     - "80:80"
     - "443:443"
     - "8000:8000"
    networks:
      modb_net:
        ipv4_address: 172.25.0.2

  modb_db:
    image: postgres:14.1-alpine
    environment:
     - POSTGRES_PASSWORD=mysecretpassword
     - POSTGRES_DB=modb
    networks:
      modb_net:
        ipv4_address: 172.25.0.4

  modb_be:
    build: https://github.com/gbriones1/modb_be.git#main
    image: modb_be
    environment:
      - db_url=postgres://postgres:mysecretpassword@172.25.0.4:5432/modb
    networks:
      modb_net:
        ipv4_address: 172.25.0.5

  modb_fe:
    build: https://github.com/gbriones1/modb_fe.git#main
    image: modb_fe
    environment:
      - API_HOST=localhost
      - API_PORT=8000
      - API_PROTOCOL=https
    networks:
      modb_net:
        ipv4_address: 172.25.0.6

networks:
  modb_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
